version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8080"
      - "443:8443"
    command:
      - start-dev
    environment:
      DB_VENDOR: POSTGRES
      DB_HOST: postgres-keycloak
      DB_NAME: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /config/certificates/certificate.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /config/certificates/key.pem
      KC_HTTPS_PORT: 8443
    depends_on:
      - postgres-keycloak
    networks:
      - app-network
    volumes:
      - ./config/keycloak/certificates:/config/certificates
  keycloak-config-cli:
    image: adorsys/keycloak-config-cli
    volumes:
      - ./config/keycloak:/config
    environment:
      KEYCLOAK_VERSION: 22.0.1
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES: /config/keycloak
    depends_on:
      - keycloak
    networks:
      - app-network
  postgres-keycloak:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: app-network